name: Hello, World!
on: 
  workflow_dispatch: {}

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: hello worlkd
        run: echo "Hello, World!"
      - name: check hour
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: | 
          echo "CURRENT_HOUR=$(date +'%H')" >> $GITHUB_ENV
      - name: echo env
        run: echo $CURRENT_HOUR
      - name: over 13
        if: ${{ ((env.CURRENT_HOUR)) > 13 }}
        run: echo "over 13"
      - name: under 11
        if: ${{ ((env.CURRENT_HOUR)) < 11 }}
        run: echo "under 11"
